=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/events_config/atreian_passport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../modifiers.xsd"/>
    <xs:include schemaLocation="../stats/stats.xsd"/>
    <xs:include schemaLocation="../import.xsd"/>
    <xs:element name="atreian_passport_templates">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="atreian_passport_template" type="LoginEventTemplate" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="LoginEventTemplate">
        <xs:sequence>
            <xs:element name="stamp_reward" type="StampReward" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>
	<xs:complexType name="StampReward">
        <xs:attribute name="item_id" type="xs:int"/>
		<xs:attribute name="count" type="xs:int"/>
		<xs:attribute name="stamp" type="xs:int"/>
		<xs:attribute name="required_level" type="xs:int" use="optional"/>
    </xs:complexType>
</xs:schema>

=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/events_config/atreian_passport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Atreian Passport 7.x
	Made By Encom
 -->
<atreian_passport_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="atreian_passport.xsd">
    <atreian_passport_template id="11" name="Bmpack_attend_01_PCbasic" type="PC_BASIC">
        <stamp_reward item_id="188072105" count="1" stamp="0"/>
        <stamp_reward item_id="164002355" count="3" stamp="1"/>
        <stamp_reward item_id="190095146" count="3" stamp="2"/>
        <stamp_reward item_id="162005023" count="15" stamp="3"/>
        <stamp_reward item_id="188074591" count="1" stamp="4"/>
        <stamp_reward item_id="188071169" count="1" stamp="5"/>
        <stamp_reward item_id="188071295" count="1" stamp="6"/>
    </atreian_passport_template>
</atreian_passport_templates>
