=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/items/item_custom_set.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../modifiers.xsd"/>
	<xs:element name="item_custom_sets">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item_custom_set" type="ItemCustomSetTemplate" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ItemCustomSetTemplate">
		<xs:sequence>
			<xs:element name="mana_stone" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="custom_enchant_value" type="xs:int" use="optional"/>
		<xs:attribute name="custom_authorize_value" type="xs:int" use="optional"/>
	</xs:complexType>
</xs:schema>

=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/items/item_custom_set.xml
<?xml version="1.0" encoding="utf-8"?>
<item_custom_sets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="item_custom_set.xsd">
	<item_custom_set id="1" name="test_set1" custom_enchant_value="1">
		<mana_stone>167000226</mana_stone>
	</item_custom_set>
	<item_custom_set id="2" name="test_set2" custom_enchant_value="5">
		<mana_stone>167000226</mana_stone>
	</item_custom_set>
	<item_custom_set id="3" name="test_set3" custom_enchant_value="10">
		<mana_stone>167000226</mana_stone>
		<mana_stone>167020024</mana_stone>
	</item_custom_set>
	<item_custom_set id="4" name="test_set4" custom_enchant_value="15">
		<mana_stone>167000226</mana_stone>
		<mana_stone>167000226</mana_stone>
		<mana_stone>167020024</mana_stone>
	</item_custom_set>
	<item_custom_set id="5" name="test_set5" custom_enchant_value="20">
		<mana_stone>167000226</mana_stone>
		<mana_stone>167000226</mana_stone>
		<mana_stone>167000226</mana_stone>
		<mana_stone>167000226</mana_stone>
		<mana_stone>167020024</mana_stone>
		<mana_stone>167020024</mana_stone>
	</item_custom_set>
	<item_custom_set id="6" name="comeback_highdeva_set1" custom_enchant_value="10">
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000775</mana_stone>
		<mana_stone>167000775</mana_stone>
	</item_custom_set>
	<item_custom_set id="7" name="comeback_highdeva_set2" custom_enchant_value="10">
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000773</mana_stone>
		<mana_stone>167000773</mana_stone>
	</item_custom_set>
	<item_custom_set id="8" name="evolution_set1" custom_enchant_value="5"/>
	<item_custom_set id="9" name="growth_sector_phy_set1" custom_enchant_value="5">
		<mana_stone>167000454</mana_stone>
		<mana_stone>167000454</mana_stone>
		<mana_stone>167000454</mana_stone>
		<mana_stone>167000454</mana_stone>
	</item_custom_set>
	<item_custom_set id="10" name="growth_sector_mag_set1" custom_enchant_value="5">
		<mana_stone>167000487</mana_stone>
		<mana_stone>167000487</mana_stone>
		<mana_stone>167000487</mana_stone>
		<mana_stone>167000487</mana_stone>
	</item_custom_set>
	<item_custom_set id="11" name="growth_sector_phy_set2" custom_enchant_value="5">
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
	</item_custom_set>
	<item_custom_set id="12" name="growth_sector_mag_set2" custom_enchant_value="5">
		<mana_stone>167000519</mana_stone>
		<mana_stone>167000519</mana_stone>
		<mana_stone>167000519</mana_stone>
		<mana_stone>167000519</mana_stone>
	</item_custom_set>
	<item_custom_set id="13" name="growth_sector_legend_set1" custom_enchant_value="5"/>
	<item_custom_set id="14" name="growth_sector_unique_set1" custom_enchant_value="8"/>
	<item_custom_set id="15" name="event_mystery_set1" custom_enchant_value="10"/>
	<item_custom_set id="16" name="test_set6" custom_enchant_value="3"/>
	<item_custom_set id="17" name="test_set7" custom_enchant_value="5"/>
	<item_custom_set id="18" name="event_wing_set1" custom_enchant_value="3"/>
	<item_custom_set id="19" name="event_wing_set2" custom_enchant_value="10"/>
	<item_custom_set id="20" name="quest_mission_lv10_phy_set1" custom_enchant_value="10">
		<mana_stone>167000230</mana_stone>
		<mana_stone>167000230</mana_stone>
	</item_custom_set>
	<item_custom_set id="21" name="quest_mission_lv10_mag_set1" custom_enchant_value="10">
		<mana_stone>167000231</mana_stone>
		<mana_stone>167000231</mana_stone>
	</item_custom_set>
	<item_custom_set id="22" name="event_wing_set3" custom_enchant_value="5"/>
	<item_custom_set id="23" name="starweapon3_set1" custom_enchant_value="5"/>
	<item_custom_set id="24" name="jumping_phy_set_65a" custom_enchant_value="15">
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
	</item_custom_set>
	<item_custom_set id="25" name="jumping_mag_set_65a" custom_enchant_value="15">
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
	</item_custom_set>
	<item_custom_set id="26" name="jumping_phy_set_45a" custom_enchant_value="15">
		<mana_stone>167000454</mana_stone>
		<mana_stone>167000454</mana_stone>
		<mana_stone>167000454</mana_stone>
		<mana_stone>167000454</mana_stone>
	</item_custom_set>
	<item_custom_set id="27" name="jumping_mag_set_45a" custom_enchant_value="15">
		<mana_stone>167000487</mana_stone>
		<mana_stone>167000487</mana_stone>
		<mana_stone>167000487</mana_stone>
		<mana_stone>167000487</mana_stone>
	</item_custom_set>
	<item_custom_set id="28" name="comeback_phy_set_70a" custom_enchant_value="15">
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
	</item_custom_set>
	<item_custom_set id="29" name="comeback_mag_set_70a" custom_enchant_value="15">
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
	</item_custom_set>
	<item_custom_set id="30" name="growup_bm_phy_set_72a" custom_enchant_value="15">
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
	</item_custom_set>
	<item_custom_set id="31" name="growup_bm_mag_set_72a" custom_enchant_value="15">
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
	</item_custom_set>
	<item_custom_set id="32" name="growup_1st_phy_set_55a" custom_enchant_value="10">
		<mana_stone>167000454</mana_stone>
		<mana_stone>167000454</mana_stone>
		<mana_stone>167000454</mana_stone>
		<mana_stone>167000454</mana_stone>
	</item_custom_set>
	<item_custom_set id="33" name="growup_1st_mag_set_55a" custom_enchant_value="10">
		<mana_stone>167000487</mana_stone>
		<mana_stone>167000487</mana_stone>
		<mana_stone>167000487</mana_stone>
		<mana_stone>167000487</mana_stone>
	</item_custom_set>
	<item_custom_set id="34" name="growup_2nd_phy_set_68a" custom_enchant_value="10">
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
		<mana_stone>167000518</mana_stone>
	</item_custom_set>
	<item_custom_set id="35" name="growup_2nd_mag_set_68a" custom_enchant_value="10">
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
		<mana_stone>167000770</mana_stone>
	</item_custom_set>
	<item_custom_set id="36" name="growup_sp_1st_phy_set_30a" custom_enchant_value="10">
		<mana_stone>167000230</mana_stone>
		<mana_stone>167000230</mana_stone>
		<mana_stone>167000230</mana_stone>
		<mana_stone>167000230</mana_stone>
	</item_custom_set>
	<item_custom_set id="37" name="growup_sp_1st_mag_set_30a" custom_enchant_value="10">
		<mana_stone>167000231</mana_stone>
		<mana_stone>167000231</mana_stone>
		<mana_stone>167000231</mana_stone>
		<mana_stone>167000231</mana_stone>
	</item_custom_set>
	<item_custom_set id="38" name="mystery_live_wi_set_75a" custom_enchant_value="15">
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
	</item_custom_set>
	<item_custom_set id="39" name="mystery_live_el_set_75a" custom_enchant_value="15">
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
	</item_custom_set>
	<item_custom_set id="40" name="mystery_live_ba_set_75a" custom_enchant_value="15">
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
	</item_custom_set>
	<item_custom_set id="41" name="mystery_live_as_set_75a" custom_enchant_value="15">
		<mana_stone>167010310</mana_stone>
		<mana_stone>167010310</mana_stone>
		<mana_stone>167010310</mana_stone>
	</item_custom_set>
	<item_custom_set id="42" name="mystery_live_ra_set_75a" custom_enchant_value="15">
		<mana_stone>167010310</mana_stone>
		<mana_stone>167010310</mana_stone>
		<mana_stone>167010310</mana_stone>
	</item_custom_set>
	<item_custom_set id="43" name="mystery_live_gu_set_75a" custom_enchant_value="15">
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
	</item_custom_set>
	<item_custom_set id="44" name="mystery_live_pr_set_75a" custom_enchant_value="15">
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
	</item_custom_set>
	<item_custom_set id="45" name="mystery_live_ch_set_75a" custom_enchant_value="15">
		<mana_stone>167010310</mana_stone>
		<mana_stone>167010310</mana_stone>
		<mana_stone>167010310</mana_stone>
	</item_custom_set>
	<item_custom_set id="46" name="mystery_live_ri_set_75a" custom_enchant_value="15">
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
		<mana_stone>167010314</mana_stone>
	</item_custom_set>
	<item_custom_set id="47" name="mystery_live_fi_set_75a" custom_enchant_value="15">
