=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/zones/zones.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1">
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="zones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="zone" type="Zone" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Zone">
		<xs:choice>
			<xs:element name="cylinder" type="Cylinder" minOccurs="0" maxOccurs="1"/>
			<xs:element name="points" type="Points" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sphere" type="Sphere" minOccurs="0" maxOccurs="1"/>
			<xs:element name="semisphere" type="Semisphere" minOccurs="0" maxOccurs="1"/>
		</xs:choice>
		<xs:attribute name="priority" type="xs:int"/>
		<xs:attribute name="siege_id" type="SiegeList"/>
		<xs:attribute name="town_id" type="xs:int" default="0"/>
		<xs:attribute name="zone_type" type="ZoneClassName"/>
		<xs:attribute name="area_type" type="AreaType"/>
		<xs:attribute name="name" type="ZoneName" use="required"/>
		<xs:attribute name="mapid" type="xs:int" use="required"/>
		<xs:attribute name="flags" type="xs:int" default="-1"/>
	</xs:complexType>
	<xs:complexType name="Points">
		<xs:sequence>
			<xs:element name="point" type="Point2D" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="top" type="xs:float"/>
		<xs:attribute name="bottom" type="xs:float"/>
	</xs:complexType>
	<xs:complexType name="Cylinder">
		<xs:attribute name="top" type="xs:float"/>
		<xs:attribute name="bottom" type="xs:float"/>
		<xs:attribute name="x" type="xs:float"/>
		<xs:attribute name="y" type="xs:float"/>
		<xs:attribute name="r" type="xs:float"/>
	</xs:complexType>
	<xs:complexType name="Sphere">
		<xs:attribute name="x" type="xs:float"/>
		<xs:attribute name="y" type="xs:float"/>
		<xs:attribute name="z" type="xs:float"/>
		<xs:attribute name="r" type="xs:float"/>
	</xs:complexType>
	<xs:complexType name="Semisphere">
		<xs:complexContent>
			<xs:extension base="Sphere"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Point2D">
		<xs:attribute name="x" type="xs:float"/>
		<xs:attribute name="y" type="xs:float"/>
	</xs:complexType>
	<xs:simpleType name="SiegeList">
		<xs:list itemType="xs:int"/>
	</xs:simpleType>
	<xs:simpleType name="ZoneClassName">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SUB"/>
			<xs:enumeration value="FLY"/>
			<xs:enumeration value="RIDE"/>
			<xs:enumeration value="ARTIFACT"/>
			<xs:enumeration value="FORT"/>
			<xs:enumeration value="LIMIT"/>
			<xs:enumeration value="ITEM_USE"/>
			<xs:enumeration value="PVP"/>
			<xs:enumeration value="DUEL"/>
			<xs:enumeration value="HOUSE"/>
			<xs:enumeration value="WEATHER"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AreaType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="POLYGON"/>
			<xs:enumeration value="CYLINDER"/>
			<xs:enumeration value="SPHERE"/>
			<xs:enumeration value="SEMISPHERE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ZoneName">
		<xs:restriction base="xs:ID"/>
	</xs:simpleType>
</xs:schema>

=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/zones/zones_quest.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
	Zone Quest
	Made By Encom
 -->
<zones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zones.xsd">
	<!-- Poeta -->
	<zone mapid="210010000" name="LF1_ITEM_USE_AREA_Q60006_210010000" area_type="SPHERE" zone_type="SUB">
		<sphere x="580.0000" y="1657.0000" z="122.000" r="25.0"/>
	</zone>
	<!-- Heiron -->
	<zone mapid="210040000" name="LF3_Q60206_210040000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2838.0000" y="2199.0000" z="138.0000" r="25.0"/>
	</zone>
	<zone mapid="210040000" name="LF3_Q61615_A_210040000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2404.0000" y="1499.0000" z="130.0000" r="25.0"/>
	</zone>
	<zone mapid="210040000" name="LF3_Q61615_B_210040000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2515.0000" y="1646.0000" z="134.0000" r="25.0"/>
	</zone>
	<zone mapid="210040000" name="LF3_Q61616_A_210040000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2466.0000" y="1596.0000" z="132.0000" r="25.0"/>
	</zone>
	<zone mapid="210040000" name="LF3_Q61619_A_210040000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2809.0000" y="2271.0000" z="142.0000" r="25.0"/>
	</zone>
	<!-- Inggison -->
	<zone mapid="210050000" name="LF4_Q60302_A_1_210050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1402.0000" y="308.0000" z="589.0000" r="25.0"/>
	</zone>
	<zone mapid="210050000" name="LF4_Q60302_A_2_210050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1361.0000" y="350.0000" z="589.0000" r="25.0"/>
	</zone>
	<zone mapid="210050000" name="LF4_Q60302_B_1_210050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1414.0000" y="351.0000" z="590.0000" r="25.0"/>
	</zone>
	<zone mapid="210050000" name="LF4_Q60302_B_2_210050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1389.0000" y="370.0000" z="590.0000" r="25.0"/>
	</zone>
	<zone mapid="210050000" name="LF4_Q60302_C_210050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1609.0000" y="509.0000" z="540.0000" r="100.0"/>
	</zone>
	<zone mapid="210050000" name="LF4_Q60302_D_210050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2530.0000" y="190.0000" z="445.0000" r="100.0"/>
	</zone>
	<zone mapid="210050000" name="LF4_Q61916_210050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1060.0000" y="1613.0000" z="408.0000" r="25.0"/>
	</zone>
	<zone mapid="210050000" name="INGGISON_COLISEUM_210050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="731.0000" y="2572.0000" z="321.0000" r="25.0"/>
	</zone>
	<!-- Beluslan -->
	<zone mapid="220040000" name="DF3_Q70201_220040000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2059.0000" y="117.0000" z="370.0000" r="25.0"/>
	</zone>
	<zone mapid="220040000" name="DF3_Q71603_220040000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1319.0000" y="1177.0000" z="232.0000" r="25.0"/>
	</zone>
	<zone mapid="220040000" name="DF3_Q71604_220040000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1787.0000" y="1346.0000" z="401.0000" r="25.0"/>
	</zone>
	<!-- Gelkmaros -->
	<zone mapid="220070000" name="DF4_Q70301_220070000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2087.0000" y="2964.0000" z="489.0000" r="25.0"/>
	</zone>
	<zone mapid="220070000" name="DF4_Q70302_B_220070000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1792.0000" y="2827.0000" z="559.0000" r="25.0"/>
	</zone>
	<zone mapid="220070000" name="DF4_Q70302_C_220070000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1496.0000" y="2592.0000" z="374.0000" r="100.0"/>
	</zone>
	<zone mapid="220070000" name="DF4_Q70302_D_220070000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1205.0000" y="2892.0000" z="481.0000" r="100.0"/>
	</zone>
	<zone mapid="220070000" name="GELKMAROS_COLISEUM_220070000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1609.0000" y="417.0000" z="321.0000" r="25.0"/>
	</zone>
	<!-- Crimson Katalam -->
	<zone mapid="800030000" name="LDF5A_ITEM_USE_AREA_KISK_L" area_type="SPHERE" zone_type="SUB">
		<sphere x="1940.0000" y="2882.0000" z="298.0000" r="200.0"/>
	</zone>
	<zone mapid="800030000" name="LDF5A_ITEM_USE_AREA_KISK_D" area_type="SPHERE" zone_type="SUB">
		<sphere x="1663.0000" y="239.0000" z="109.0000" r="200.0"/>
	</zone>
	<!-- Lakrum -->
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q60502_A_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1477.0000" y="527.0000" z="199.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q60503_A_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1233.0000" y="900.0000" z="296.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q60503_B_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1277.0000" y="994.0000" z="274.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q60504_A_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="682.0000" y="356.0000" z="290.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q60504_B_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="737.0000" y="239.0000" z="277.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_ITEMUSEAREA_Q60505A" area_type="SPHERE" zone_type="SUB">
		<sphere x="259.0000" y="1376.0000" z="319.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q62505_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2366.0000" y="724.0000" z="279.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_ITEMUSEAREA_Q62545A" area_type="SPHERE" zone_type="SUB">
        <sphere x="2769.0000" y="1456.0000" z="197.0000" r="25.0"/>
    </zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q70502_A_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1394.0000" y="2417.0000" z="199.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q70503_A_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1296.0000" y="2196.0000" z="227.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q70503_B_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="1237.0000" y="2122.0000" z="233.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q70504_A_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="574.0000" y="2683.0000" z="246.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q70504_B_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="642.0000" y="2732.0000" z="253.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_ITEMUSEAREA_Q70505A" area_type="SPHERE" zone_type="SUB">
		<sphere x="247.0000" y="1686.0000" z="319.0000" r="25.0"/>
	</zone>
	<zone mapid="800050000" name="LDF7_SENSORY_AREA_Q72505_800050000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2400.0000" y="2438.0000" z="293.0000" r="25.0"/>
	</zone>
	<!-- Demaha -->
	<zone mapid="800060000" name="LDF8_D_ITEMUSEAREA_Q60605A" area_type="SPHERE" zone_type="SUB">
		<sphere x="1846.0000" y="1350.0000" z="616.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="LDF8_D_ITEMUSEAREA_Q70605A" area_type="SPHERE" zone_type="SUB">
		<sphere x="1978.0000" y="1409.0000" z="615.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="LDF8_ITEMUSEAREA_Q62903" area_type="SPHERE" zone_type="SUB">
		<sphere x="1773.0000" y="916.0000" z="581.0000" r="50.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q63003C" area_type="SPHERE" zone_type="SUB">
		<sphere x="1389.0000" y="1170.0000" z="610.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q63008A" area_type="SPHERE" zone_type="SUB">
		<sphere x="981.0000" y="2576.0000" z="543.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q63008B" area_type="SPHERE" zone_type="SUB">
		<sphere x="1132.0000" y="2561.0000" z="559.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q63008C" area_type="SPHERE" zone_type="SUB">
		<sphere x="1000.0000" y="2944.0000" z="544.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q63010A" area_type="SPHERE" zone_type="SUB">
		<sphere x="2751.0000" y="2551.0000" z="636.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q63010B" area_type="SPHERE" zone_type="SUB">
		<sphere x="2509.0000" y="2882.0000" z="629.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q63010C" area_type="SPHERE" zone_type="SUB">
		<sphere x="2776.0000" y="1625.0000" z="696.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="LDF8_SENSORY_AREA_A_Q63015_800060000" area_type="SPHERE" zone_type="SUB">
		<sphere x="401.0000" y="1488.0000" z="781.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="LDF8_SENSORY_AREA_B_Q63015_800060000" area_type="SPHERE" zone_type="SUB">
		<sphere x="401.0000" y="1488.0000" z="781.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="LDF8_SENSORY_AREA_C_Q63015_800060000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2934.0000" y="1494.0000" z="703.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="LDF8_SENSORY_AREA_A_Q63905_800060000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2957.0000" y="2041.0000" z="682.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="LDF8_SENSORY_AREA_B_Q63905_800060000" area_type="SPHERE" zone_type="SUB">
		<sphere x="2946.0000" y="1753.0000" z="679.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q73008A" area_type="SPHERE" zone_type="SUB">
		<sphere x="1035.0000" y="2515.0000" z="542.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q73008B" area_type="SPHERE" zone_type="SUB">
		<sphere x="1208.0000" y="2635.0000" z="556.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q73008C" area_type="SPHERE" zone_type="SUB">
		<sphere x="931.0000" y="2877.0000" z="544.0000" r="25.0"/>
	</zone>
	<zone mapid="800060000" name="ITEMUSEAREA_Q73010A" area_type="SPHERE" zone_type="SUB">
		<sphere x="2923.0000" y="2599.0000" z="627.0000" r="25.0"/>
	</zone>
