=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/monster_core/monster_core_templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../modifiers.xsd"/>
    <xs:include schemaLocation="../stats/stats.xsd"/>
    <xs:include schemaLocation="../import.xsd"/>
    <xs:element name="monster_core_templates">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="monster_core_template" type="MonsterCoreTemplate" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="MonsterCoreTemplate">
        <xs:sequence>
            <xs:element name="core_list" type="MonsterCoreList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="category" type="xs:int"/>
        <xs:attribute name="maxRank" type="xs:int"/>
        <xs:attribute name="quality" type="MonsterCoreType" use="required"/>
        <xs:attribute name="itemId" type="xs:int"/>
    </xs:complexType>
    <xs:complexType name="MonsterCoreList">
        <xs:attribute name="id" type="xs:int"/>
        <xs:attribute name="level" type="xs:int"/>
        <xs:attribute name="stat" type="modifiersenum" use="required"/>
        <xs:attribute name="value" type="xs:int"/>
    </xs:complexType>
    <xs:simpleType name="MonsterCoreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GOLD"/>
            <xs:enumeration value="SILVER"/>
            <xs:enumeration value="BRONZE"/>
			<xs:enumeration value="PLATINUM"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/monster_core/monster_core_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Cubic 7.x
	Made By Encom
 -->
<monster_core_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="monster_core_templates.xsd">
    <monster_core_template id="1" name="Golden Garkion's Life Cubic" quality="GOLD" maxRank="5" category="100" itemId="188200023">
		<core_list id="1" level="5" stat="MAXHP" value="429"/>
		<core_list id="2" level="10" stat="MAXHP" value="613"/>
		<core_list id="3" level="15" stat="MAXHP" value="875"/>
		<core_list id="4" level="20" stat="MAXHP" value="1330"/>
		<core_list id="5" level="25" stat="MAXHP" value="1900"/>
	</monster_core_template>
	<monster_core_template id="2" name="Silver Garkion's Life Cubic" quality="SILVER" maxRank="5" category="100" itemId="188200024">
		<core_list id="1" level="10" stat="MAXHP" value="420"/>
		<core_list id="2" level="20" stat="MAXHP" value="600"/>
		<core_list id="3" level="30" stat="MAXHP" value="858"/>
		<core_list id="4" level="40" stat="MAXHP" value="1225"/>
		<core_list id="5" level="50" stat="MAXHP" value="1650"/>
	</monster_core_template>
	<monster_core_template id="3" name="Bronze Garkion's Life Cubic" quality="BRONZE" maxRank="5" category="100" itemId="188200025">
		<core_list id="1" level="20" stat="MAXHP" value="336"/>
		<core_list id="2" level="40" stat="MAXHP" value="480"/>
		<core_list id="3" level="60" stat="MAXHP" value="686"/>
		<core_list id="4" level="80" stat="MAXHP" value="980"/>
		<core_list id="5" level="100" stat="MAXHP" value="1400"/>
	</monster_core_template>
	<monster_core_template id="4" name="Golden Agrint's Mind Cubic" quality="GOLD" maxRank="5" category="101" itemId="188200026">
		<core_list id="1" level="5" stat="MAXMP" value="300"/>
		<core_list id="2" level="10" stat="MAXMP" value="429"/>
		<core_list id="3" level="15" stat="MAXMP" value="613"/>
		<core_list id="4" level="20" stat="MAXMP" value="931"/>
		<core_list id="5" level="25" stat="MAXMP" value="1330"/>
	</monster_core_template>
	<monster_core_template id="5" name="Silver Agrint's Mind Cubic" quality="SILVER" maxRank="5" category="101" itemId="188200027">
		<core_list id="1" level="10" stat="MAXMP" value="294"/>
		<core_list id="2" level="20" stat="MAXMP" value="420"/>
		<core_list id="3" level="30" stat="MAXMP" value="600"/>
		<core_list id="4" level="40" stat="MAXMP" value="858"/>
		<core_list id="5" level="50" stat="MAXMP" value="1155"/>
	</monster_core_template>
	<monster_core_template id="6" name="Bronze Agrint's Mind Cubic" quality="BRONZE" maxRank="5" category="101" itemId="188200028">
		<core_list id="1" level="20" stat="MAXMP" value="235"/>
		<core_list id="2" level="40" stat="MAXMP" value="336"/>
		<core_list id="3" level="60" stat="MAXMP" value="480"/>
		<core_list id="4" level="80" stat="MAXMP" value="686"/>
		<core_list id="5" level="100" stat="MAXMP" value="980"/>
	</monster_core_template>
	<monster_core_template id="7" name="Golden Trico's Blessing Cubic" quality="GOLD" maxRank="5" category="102" itemId="188200029">
		<core_list id="1" level="5" stat="HEAL_BOOST" value="10"/>
		<core_list id="2" level="10" stat="HEAL_BOOST" value="15"/>
		<core_list id="3" level="15" stat="HEAL_BOOST" value="21"/>
		<core_list id="4" level="20" stat="HEAL_BOOST" value="32"/>
		<core_list id="5" level="25" stat="HEAL_BOOST" value="46"/>
	</monster_core_template>
	<monster_core_template id="8" name="Silver Trico's Blessing Cubic" quality="SILVER" maxRank="5" category="102" itemId="188200030">
		<core_list id="1" level="10" stat="HEAL_BOOST" value="10"/>
		<core_list id="2" level="20" stat="HEAL_BOOST" value="14"/>
		<core_list id="3" level="30" stat="HEAL_BOOST" value="21"/>
		<core_list id="4" level="40" stat="HEAL_BOOST" value="29"/>
		<core_list id="5" level="50" stat="HEAL_BOOST" value="40"/>
	</monster_core_template>
	<monster_core_template id="9" name="Bronze Trico's Blessing Cubic" quality="BRONZE" maxRank="5" category="102" itemId="188200031">
		<core_list id="1" level="20" stat="HEAL_BOOST" value="8"/>
		<core_list id="2" level="40" stat="HEAL_BOOST" value="12"/>
		<core_list id="3" level="60" stat="HEAL_BOOST" value="16"/>
		<core_list id="4" level="80" stat="HEAL_BOOST" value="24"/>
		<core_list id="5" level="100" stat="HEAL_BOOST" value="34"/>
	</monster_core_template>
	<monster_core_template id="10" name="Golden Worg's Lunacy Cubic" quality="GOLD" maxRank="5" category="103" itemId="188200032">
		<core_list id="1" level="5" stat="PHYSICAL_POWER_BOOST" value="33"/>
		<core_list id="2" level="10" stat="PHYSICAL_POWER_BOOST" value="47"/>
		<core_list id="3" level="15" stat="PHYSICAL_POWER_BOOST" value="67"/>
		<core_list id="4" level="20" stat="PHYSICAL_POWER_BOOST" value="101"/>
		<core_list id="5" level="25" stat="PHYSICAL_POWER_BOOST" value="144"/>
	</monster_core_template>
	<monster_core_template id="11" name="Silver Worg's Lunacy Cubic" quality="SILVER" maxRank="5" category="103" itemId="188200033">
		<core_list id="1" level="10" stat="PHYSICAL_POWER_BOOST" value="32"/>
		<core_list id="2" level="20" stat="PHYSICAL_POWER_BOOST" value="46"/>
		<core_list id="3" level="30" stat="PHYSICAL_POWER_BOOST" value="65"/>
		<core_list id="4" level="40" stat="PHYSICAL_POWER_BOOST" value="93"/>
		<core_list id="5" level="50" stat="PHYSICAL_POWER_BOOST" value="125"/>
	</monster_core_template>
	<monster_core_template id="12" name="Bronze Worg's Lunacy Cubic" quality="BRONZE" maxRank="5" category="103" itemId="188200034">
		<core_list id="1" level="20" stat="PHYSICAL_POWER_BOOST" value="26"/>
		<core_list id="2" level="40" stat="PHYSICAL_POWER_BOOST" value="36"/>
		<core_list id="3" level="60" stat="PHYSICAL_POWER_BOOST" value="52"/>
		<core_list id="4" level="80" stat="PHYSICAL_POWER_BOOST" value="74"/>
		<core_list id="5" level="100" stat="PHYSICAL_POWER_BOOST" value="106"/>
	</monster_core_template>
	<monster_core_template id="13" name="Golden Griffon's Wisdom Cubic" quality="GOLD" maxRank="5" category="104" itemId="188200035">
		<core_list id="1" level="5" stat="MAGICAL_POWER_BOOST" value="33"/>
		<core_list id="2" level="10" stat="MAGICAL_POWER_BOOST" value="47"/>
		<core_list id="3" level="15" stat="MAGICAL_POWER_BOOST" value="67"/>
		<core_list id="4" level="20" stat="MAGICAL_POWER_BOOST" value="101"/>
		<core_list id="5" level="25" stat="MAGICAL_POWER_BOOST" value="144"/>
	</monster_core_template>
	<monster_core_template id="14" name="Silver Griffon's Wisdom Cubic" quality="SILVER" maxRank="5" category="104" itemId="188200036">
		<core_list id="1" level="10" stat="MAGICAL_POWER_BOOST" value="32"/>
		<core_list id="2" level="20" stat="MAGICAL_POWER_BOOST" value="46"/>
		<core_list id="3" level="30" stat="MAGICAL_POWER_BOOST" value="65"/>
		<core_list id="4" level="40" stat="MAGICAL_POWER_BOOST" value="93"/>
		<core_list id="5" level="50" stat="MAGICAL_POWER_BOOST" value="125"/>
	</monster_core_template>
	<monster_core_template id="15" name="Bronze Griffon's Wisdom Cubic" quality="BRONZE" maxRank="5" category="104" itemId="188200037">
		<core_list id="1" level="20" stat="MAGICAL_POWER_BOOST" value="26"/>
		<core_list id="2" level="40" stat="MAGICAL_POWER_BOOST" value="36"/>
		<core_list id="3" level="60" stat="MAGICAL_POWER_BOOST" value="52"/>
		<core_list id="4" level="80" stat="MAGICAL_POWER_BOOST" value="74"/>
		<core_list id="5" level="100" stat="MAGICAL_POWER_BOOST" value="106"/>
	</monster_core_template>
	<monster_core_template id="16" name="Golden Starturtle's Protection Cubic" quality="GOLD" maxRank="5" category="105" itemId="188200038">
		<core_list id="1" level="5" stat="PHYSICAL_POWER_BOOST_RESIST" value="33"/>
		<core_list id="2" level="10" stat="PHYSICAL_POWER_BOOST_RESIST" value="47"/>
		<core_list id="3" level="15" stat="PHYSICAL_POWER_BOOST_RESIST" value="67"/>
		<core_list id="4" level="20" stat="PHYSICAL_POWER_BOOST_RESIST" value="101"/>
		<core_list id="5" level="25" stat="PHYSICAL_POWER_BOOST_RESIST" value="144"/>
	</monster_core_template>
	<monster_core_template id="17" name="Silver Starturtle's Protection Cubic" quality="SILVER" maxRank="5" category="105" itemId="188200039">
		<core_list id="1" level="10" stat="PHYSICAL_POWER_BOOST_RESIST" value="32"/>
		<core_list id="2" level="20" stat="PHYSICAL_POWER_BOOST_RESIST" value="46"/>
		<core_list id="3" level="30" stat="PHYSICAL_POWER_BOOST_RESIST" value="65"/>
		<core_list id="4" level="40" stat="PHYSICAL_POWER_BOOST_RESIST" value="93"/>
		<core_list id="5" level="50" stat="PHYSICAL_POWER_BOOST_RESIST" value="125"/>
	</monster_core_template>
	<monster_core_template id="18" name="Bronze Starturtle's Protection Cubic" quality="BRONZE" maxRank="5" category="105" itemId="188200040">
		<core_list id="1" level="20" stat="PHYSICAL_POWER_BOOST_RESIST" value="26"/>
		<core_list id="2" level="40" stat="PHYSICAL_POWER_BOOST_RESIST" value="36"/>
		<core_list id="3" level="60" stat="PHYSICAL_POWER_BOOST_RESIST" value="52"/>
		<core_list id="4" level="80" stat="PHYSICAL_POWER_BOOST_RESIST" value="74"/>
		<core_list id="5" level="100" stat="PHYSICAL_POWER_BOOST_RESIST" value="106"/>
	</monster_core_template>
	<monster_core_template id="19" name="Golden Scolopen's Aegis Cubic" quality="GOLD" maxRank="5" category="106" itemId="188200041">
		<core_list id="1" level="5" stat="MAGICAL_POWER_BOOST_RESIST" value="33"/>
		<core_list id="2" level="10" stat="MAGICAL_POWER_BOOST_RESIST" value="47"/>
		<core_list id="3" level="15" stat="MAGICAL_POWER_BOOST_RESIST" value="67"/>
		<core_list id="4" level="20" stat="MAGICAL_POWER_BOOST_RESIST" value="101"/>
		<core_list id="5" level="25" stat="MAGICAL_POWER_BOOST_RESIST" value="144"/>
	</monster_core_template>
	<monster_core_template id="20" name="Silver Scolopen's Aegis Cubic" quality="SILVER" maxRank="5" category="106" itemId="188200042">
		<core_list id="1" level="10" stat="MAGICAL_POWER_BOOST_RESIST" value="32"/>
		<core_list id="2" level="20" stat="MAGICAL_POWER_BOOST_RESIST" value="46"/>
		<core_list id="3" level="30" stat="MAGICAL_POWER_BOOST_RESIST" value="65"/>
