=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/ride/ride.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rides">
        <xs:complexType>
           <xs:sequence>
               <xs:element name="ride_info" type="RideInfo" minOccurs="0" maxOccurs="unbounded"/>
           </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="RideType">
        <xs:restriction base="xs:int">
           <xs:minInclusive value="0"/>
           <xs:maxInclusive value="99"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="RideInfo">
        <xs:sequence>
            <xs:element name="ridebound" type="RideBound" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
	    <xs:attribute name="type" type="RideType"/>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="cost_fp" type="xs:int"/>
        <xs:attribute name="start_fp" type="xs:int"/>
	    <xs:attribute name="move_speed" type="xs:float" use="optional" default="0"/>
	    <xs:attribute name="fly_speed" type="xs:float" use="optional" default="0"/>
        <xs:attribute name="sprint_speed" type="xs:float" use="optional" default="0"/>
		<xs:attribute name="buff_id" type="xs:int" use="optional" default="0"/>
    </xs:complexType>
    <xs:complexType name="RideBound">
  	    <xs:attribute name="altitude" type="xs:float"/>
        <xs:attribute name="upper" type="xs:float"/>
        <xs:attribute name="side" type="xs:float"/>
        <xs:attribute name="front" type="xs:float"/>
    </xs:complexType>
</xs:schema>

=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/ride/ride.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
	Rides
	Made By Encom
 -->
<rides xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ride.xsd">
    <ride_info id="2000000" type="0" move_speed="12.0" fly_speed="16.0" sprint_speed="15.0" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000001" type="0" move_speed="12.0" fly_speed="16.0" sprint_speed="15.0" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000002" type="0" move_speed="12.0" fly_speed="16.0" sprint_speed="15.0" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000003" type="1" move_speed="12.3" fly_speed="16.0" sprint_speed="14.7" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000004" type="1" move_speed="12.6" fly_speed="16.0" sprint_speed="15.0" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000005" type="0" move_speed="11.1" fly_speed="14.0" start_fp="0" cost_fp="0">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000006" type="0" move_speed="12.0" fly_speed="14.5" sprint_speed="14.0" start_fp="12" cost_fp="12">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000007" type="0" move_speed="12.6" fly_speed="15.0" sprint_speed="15.0" start_fp="12" cost_fp="12">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000008" type="2" move_speed="12.4" fly_speed="16.0" sprint_speed="14.9" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000009" type="2" move_speed="12.7" fly_speed="16.0" sprint_speed="15.2" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000010" type="0" move_speed="10.8" fly_speed="13.5" start_fp="0" cost_fp="0">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000011" type="0" move_speed="11.4" fly_speed="15.0" sprint_speed="13.6" start_fp="12" cost_fp="12">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000012" type="0" move_speed="12.0" fly_speed="16.0" sprint_speed="14.4" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000013" type="0" move_speed="11.4" fly_speed="15.0" sprint_speed="13.6" start_fp="12" cost_fp="12">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000014" type="1" move_speed="9.0" fly_speed="13.0" start_fp="0" cost_fp="0">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000015" type="0" move_speed="12.6" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000016" type="0" move_speed="12.0" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000017" type="0" move_speed="12.0" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000018" type="0" move_speed="12.0" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000019" type="0" move_speed="12.0" fly_speed="16.0" sprint_speed="15.0" start_fp="12" cost_fp="12">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000020" type="2" move_speed="12.0" fly_speed="16.0" sprint_speed="14.5" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000021" type="1" move_speed="11.9" fly_speed="16.0" sprint_speed="14.2" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000022" type="0" move_speed="11.7" fly_speed="15.5" sprint_speed="14.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000023" type="2" move_speed="12.4" fly_speed="16.0" sprint_speed="14.9" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000024" type="1" move_speed="12.3" fly_speed="16.0" sprint_speed="14.7" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000025" type="1" move_speed="14.0" fly_speed="16.0" sprint_speed="16.0" start_fp="1" cost_fp="1">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000026" type="0" move_speed="12.0" fly_speed="16.0" sprint_speed="15.0" start_fp="10" cost_fp="10">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000027" type="1" move_speed="14.0" fly_speed="16.0" sprint_speed="16.0" start_fp="1" cost_fp="1">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000028" type="1" move_speed="12.0" fly_speed="16.0" sprint_speed="14.0" start_fp="9" cost_fp="9">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000029" type="1" move_speed="12.0" fly_speed="16.0" sprint_speed="14.0" start_fp="9" cost_fp="9">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000030" type="1" move_speed="11.9" fly_speed="16.0" sprint_speed="14.0" start_fp="12" cost_fp="12">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000031" type="1" move_speed="12.6" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000032" type="2" move_speed="12.8" fly_speed="16.0" sprint_speed="15.0" start_fp="8" cost_fp="8">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000033" type="2" move_speed="12.2" fly_speed="16.0" sprint_speed="14.5" start_fp="9" cost_fp="9">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000034" type="2" move_speed="14.0" fly_speed="16.0" sprint_speed="16.0" start_fp="1" cost_fp="1">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000035" type="2" move_speed="12.8" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000036" type="0" move_speed="12.6" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000037" type="0" move_speed="12.6" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000038" type="0" move_speed="12.6" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000039" type="0" move_speed="12.6" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
        <ridebound front="0.724" side="0.724" upper="2.5" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000040" type="2" move_speed="12.8" fly_speed="16.0" sprint_speed="15.0" start_fp="8" cost_fp="8">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000041" type="1" move_speed="10.8" fly_speed="13.5" start_fp="0" cost_fp="0">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000042" type="1" move_speed="12.8" fly_speed="16.0" sprint_speed="15.0" start_fp="8" cost_fp="8">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000043" type="2" move_speed="11.9" fly_speed="16.0" sprint_speed="14.0" start_fp="12" cost_fp="12">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000044" type="1" move_speed="12.8" fly_speed="16.0" sprint_speed="15.0" start_fp="6" cost_fp="6">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000045" type="1" move_speed="12.8" fly_speed="16.0" sprint_speed="15.0" start_fp="6" cost_fp="6">
        <ridebound front="0.724" side="0.724" upper="3.0" altitude="0.5"/>
    </ride_info>
    <ride_info id="2000046" type="0" move_speed="12.6" fly_speed="16.0" sprint_speed="15.0" start_fp="11" cost_fp="11">
