=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/stats/stats.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd"/>
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="player_stats_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="player_stats" type="playerStatsTemplateType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="summon_stats_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="summon_stats" type="summonStatsTemplateType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="playerStatsTemplateType">
		<xs:sequence>
			<xs:element name="stats_template" type="playerStatsTemplate" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="class" type="playerClass" use="required"/>
		<xs:attribute name="level" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="playerStatsTemplate">
		<xs:complexContent>
			<xs:extension base="statsTemplate">
				<xs:attribute name="power" type="xs:int" use="required"/>
				<xs:attribute name="health" type="xs:int" use="required"/>
				<xs:attribute name="agility" type="xs:int" use="required"/>
				<xs:attribute name="accuracy" type="xs:int" use="required"/>
				<xs:attribute name="knowledge" type="xs:int" use="required"/>
				<xs:attribute name="will" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="summonStatsTemplateType">
		<xs:sequence>
			<xs:element name="stats_template" type="summonStatsTemplate" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="npc_id_light" type="xs:int"/>
		<xs:attribute name="npc_id_dark" type="xs:int"/>
		<xs:attribute name="level" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="summonStatsTemplate">
		<xs:complexContent>
			<xs:extension base="statsTemplate">
				<xs:attribute name="pdefense" type="xs:int" use="required"/>
				<xs:attribute name="mresist" type="xs:int" use="required"/>
				<xs:attribute name="mcrit" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="statsTemplate" abstract="true">
		<xs:attribute name="maxHp" type="xs:int" use="required"/>
		<xs:attribute name="maxMp" type="xs:int"/>
		<xs:attribute name="walk_speed" type="xs:float"/>
		<xs:attribute name="run_speed" type="xs:float"/>
		<xs:attribute name="fly_speed" type="xs:float"/>
		<xs:attribute name="attack_speed" type="xs:float"/>
		<xs:attribute name="evasion" type="xs:int"/>
		<xs:attribute name="block" type="xs:int"/>
		<xs:attribute name="parry" type="xs:int"/>
		<xs:attribute name="main_hand_attack" type="xs:int"/>
		<xs:attribute name="main_hand_accuracy" type="xs:int"/>
		<xs:attribute name="main_hand_crit_rate" type="xs:int"/>
		<xs:attribute name="magic_accuracy" type="xs:int"/>
		<xs:attribute name="crit_spell" type="xs:int"/>
	</xs:complexType>
</xs:schema>

=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/stats/summon/magmaspirit-templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Magma Spirit Stats 7.x
	Made By Rinzler [Encom]
 -->
<summon_stats_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../stats.xsd">
	<!-- ********************* -->
	<!-- MAGMA SPIRIT LEVEL: 1 -->
	<!-- ********************* -->
	<summon_stats npc_id_dark="833366" level="50">
        <stats_template maxHp="20000" pdefense="1600" mresist="1750" main_hand_attack="2700" run_speed="12.0" main_hand_accuracy="1650" main_hand_crit_rate="50" magic_accuracy="1150" evasion="1250" mcrit="9" parry="0"/>
    </summon_stats>
    <summon_stats npc_id_dark="833366" level="51">
        <stats_template maxHp="20200" pdefense="1650" mresist="1800" main_hand_attack="2750" run_speed="12.0" main_hand_accuracy="1700" main_hand_crit_rate="50" magic_accuracy="1200" evasion="1300" mcrit="9" parry="0"/>
    </summon_stats>
    <summon_stats npc_id_dark="833366" level="52">
        <stats_template maxHp="20400" pdefense="1700" mresist="1850" main_hand_attack="2800" run_speed="12.0" main_hand_accuracy="1750" main_hand_crit_rate="50" magic_accuracy="1250" evasion="1350" mcrit="9" parry="0"/>
    </summon_stats>
    <summon_stats npc_id_dark="833366" level="53">
        <stats_template maxHp="20600" pdefense="1750" mresist="1900" main_hand_attack="2850" run_speed="12.0" main_hand_accuracy="1800" main_hand_crit_rate="50" magic_accuracy="1300" evasion="1400" mcrit="9" parry="0"/>
    </summon_stats>
    <summon_stats npc_id_dark="833366" level="54">
        <stats_template maxHp="20800" pdefense="1850" mresist="1950" main_hand_attack="2900" run_speed="12.0" main_hand_accuracy="1850" main_hand_crit_rate="50" magic_accuracy="1350" evasion="1450" mcrit="9" parry="0"/>
    </summon_stats>
	
	<!-- ********************* -->
	<!-- MAGMA SPIRIT LEVEL: 2 -->
	<!-- ********************* -->
    <summon_stats npc_id_dark="833368" level="55">
        <stats_template maxHp="21000" pdefense="1900" mresist="2000" main_hand_attack="2950" run_speed="12.0" main_hand_accuracy="1900" main_hand_crit_rate="50" magic_accuracy="1400" evasion="1500" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833368" level="56">
        <stats_template maxHp="21200" pdefense="1950" mresist="2050" main_hand_attack="3000" run_speed="12.0" main_hand_accuracy="1950" main_hand_crit_rate="50" magic_accuracy="1450" evasion="1550" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833368" level="57">
        <stats_template maxHp="21400" pdefense="2000" mresist="2100" main_hand_attack="3050" run_speed="12.0" main_hand_accuracy="2000" main_hand_crit_rate="50" magic_accuracy="1500" evasion="1600" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833368" level="58">
        <stats_template maxHp="21600" pdefense="2050" mresist="2150" main_hand_attack="3100" run_speed="12.0" main_hand_accuracy="2050" main_hand_crit_rate="50" magic_accuracy="1550" evasion="1650" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833368" level="59">
        <stats_template maxHp="21800" pdefense="2100" mresist="2200" main_hand_attack="3150" run_speed="12.0" main_hand_accuracy="2100" main_hand_crit_rate="50" magic_accuracy="1600" evasion="1700" mcrit="9" parry="0"/>
    </summon_stats>
	
	<!-- ********************* -->
	<!-- MAGMA SPIRIT LEVEL: 3 -->
	<!-- ********************* -->
    <summon_stats npc_id_dark="833370" level="60">
        <stats_template maxHp="22000" pdefense="2150" mresist="2250" main_hand_attack="3200" run_speed="12.0" main_hand_accuracy="2150" main_hand_crit_rate="50" magic_accuracy="1650" evasion="1750" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833370" level="61">
        <stats_template maxHp="22200" pdefense="2200" mresist="2300" main_hand_attack="3250" run_speed="12.0" main_hand_accuracy="2200" main_hand_crit_rate="50" magic_accuracy="1700" evasion="1800" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833370" level="62">
        <stats_template maxHp="22400" pdefense="2250" mresist="2350" main_hand_attack="3300" run_speed="12.0" main_hand_accuracy="2250" main_hand_crit_rate="50" magic_accuracy="1750" evasion="1850" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833370" level="63">
        <stats_template maxHp="22600" pdefense="2300" mresist="2400" main_hand_attack="3350" run_speed="12.0" main_hand_accuracy="2300" main_hand_crit_rate="50" magic_accuracy="1800" evasion="1900" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833370" level="64">
        <stats_template maxHp="22800" pdefense="2350" mresist="2450" main_hand_attack="3400" run_speed="12.0" main_hand_accuracy="2350" main_hand_crit_rate="50" magic_accuracy="1850" evasion="1950" mcrit="9" parry="0"/>
    </summon_stats>
	
	<!-- ********************* -->
	<!-- MAGMA SPIRIT LEVEL: 4 -->
	<!-- ********************* -->
	<summon_stats npc_id_dark="833262" level="65">
        <stats_template maxHp="23000" pdefense="2400" mresist="2500" main_hand_attack="3450" run_speed="12.0" main_hand_accuracy="2400" main_hand_crit_rate="50" magic_accuracy="1900" evasion="2000" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="66">
        <stats_template maxHp="23200" pdefense="2450" mresist="2550" main_hand_attack="3500" run_speed="12.0" main_hand_accuracy="2450" main_hand_crit_rate="50" magic_accuracy="1950" evasion="2050" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="67">
        <stats_template maxHp="23400" pdefense="2500" mresist="2600" main_hand_attack="3550" run_speed="12.0" main_hand_accuracy="2500" main_hand_crit_rate="50" magic_accuracy="2000" evasion="2100" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="68">
        <stats_template maxHp="23600" pdefense="2550" mresist="2650" main_hand_attack="3600" run_speed="12.0" main_hand_accuracy="2550" main_hand_crit_rate="50" magic_accuracy="2050" evasion="2150" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="69">
        <stats_template maxHp="23800" pdefense="2600" mresist="2700" main_hand_attack="3650" run_speed="12.0" main_hand_accuracy="2600" main_hand_crit_rate="50" magic_accuracy="2100" evasion="2200" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="70">
        <stats_template maxHp="24000" pdefense="2650" mresist="2750" main_hand_attack="3700" run_speed="12.0" main_hand_accuracy="2650" main_hand_crit_rate="50" magic_accuracy="2150" evasion="2250" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="71">
        <stats_template maxHp="24200" pdefense="2700" mresist="2800" main_hand_attack="3750" run_speed="12.0" main_hand_accuracy="2700" main_hand_crit_rate="50" magic_accuracy="2200" evasion="2300" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="72">
        <stats_template maxHp="24400" pdefense="2750" mresist="2850" main_hand_attack="3800" run_speed="12.0" main_hand_accuracy="2750" main_hand_crit_rate="50" magic_accuracy="2250" evasion="2350" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="73">
        <stats_template maxHp="24600" pdefense="2800" mresist="2900" main_hand_attack="3850" run_speed="12.0" main_hand_accuracy="2800" main_hand_crit_rate="50" magic_accuracy="2300" evasion="2400" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="74">
        <stats_template maxHp="24800" pdefense="2850" mresist="2950" main_hand_attack="3900" run_speed="12.0" main_hand_accuracy="2850" main_hand_crit_rate="50" magic_accuracy="2350" evasion="2450" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="75">
        <stats_template maxHp="25000" pdefense="2900" mresist="3000" main_hand_attack="3950" run_speed="12.0" main_hand_accuracy="2900" main_hand_crit_rate="50" magic_accuracy="2400" evasion="2500" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="76">
        <stats_template maxHp="25200" pdefense="2950" mresist="3050" main_hand_attack="3950" run_speed="12.0" main_hand_accuracy="2950" main_hand_crit_rate="50" magic_accuracy="2450" evasion="2550" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="77">
        <stats_template maxHp="25400" pdefense="3000" mresist="3100" main_hand_attack="4000" run_speed="12.0" main_hand_accuracy="3000" main_hand_crit_rate="50" magic_accuracy="2500" evasion="2600" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="78">
        <stats_template maxHp="25600" pdefense="3050" mresist="3150" main_hand_attack="4050" run_speed="12.0" main_hand_accuracy="3050" main_hand_crit_rate="50" magic_accuracy="2550" evasion="2650" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="79">
        <stats_template maxHp="25800" pdefense="3100" mresist="3200" main_hand_attack="4100" run_speed="12.0" main_hand_accuracy="3100" main_hand_crit_rate="50" magic_accuracy="2600" evasion="2700" mcrit="9" parry="0"/>
    </summon_stats>
	<summon_stats npc_id_dark="833262" level="80">
        <stats_template maxHp="26000" pdefense="3150" mresist="3250" main_hand_attack="4150" run_speed="12.0" main_hand_accuracy="3150" main_hand_crit_rate="50" magic_accuracy="2650" evasion="2750" mcrit="9" parry="0"/>
    </summon_stats>
</summon_stats_templates>

=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/stats/player/muse-templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<player_stats_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../stats.xsd">
	<!-- Checked By Encom 28/07/2013 -->
	<player_stats class="MUSE" level="1">
		<stats_template maxHp="179" maxMp="375" power="95" health="95" agility="100" accuracy="100" knowledge="100" will="110" walk_speed="1.5" run_speed="6" fly_speed="9" attack_speed="1.5" evasion="58" block="58" parry="58" main_hand_attack="17" main_hand_accuracy="188" main_hand_crit_rate="2" magic_accuracy="14" crit_spell="50"/>
	</player_stats>
	<!-- Checked By Encom 28/07/2013 -->
	<player_stats class="MUSE" level="2">
		<stats_template maxHp="216" maxMp="480" power="95" health="95" agility="100" accuracy="100" knowledge="100" will="110" walk_speed="1.5" run_speed="6" fly_speed="9" attack_speed="1.5" evasion="86" block="86" parry="86" main_hand_attack="17" main_hand_accuracy="206" main_hand_crit_rate="2" magic_accuracy="28" crit_spell="50"/>
	</player_stats>
	<!-- Checked By Encom 28/07/2013 -->
	<player_stats class="MUSE" level="3">
		<stats_template maxHp="255" maxMp="585" power="95" health="95" agility="100" accuracy="100" knowledge="100" will="110" walk_speed="1.5" run_speed="6" fly_speed="9" attack_speed="1.5" evasion="99" block="99" parry="99" main_hand_attack="17" main_hand_accuracy="214" main_hand_crit_rate="2" magic_accuracy="42" crit_spell="50"/>
	</player_stats>
	<!-- Checked By Encom 28/07/2013 -->
	<player_stats class="MUSE" level="4">
		<stats_template maxHp="296" maxMp="690" power="95" health="95" agility="100" accuracy="100" knowledge="100" will="110" walk_speed="1.5" run_speed="6" fly_speed="9" attack_speed="1.5" evasion="111" block="111" parry="111" main_hand_attack="17" main_hand_accuracy="222" main_hand_crit_rate="2" magic_accuracy="57" crit_spell="50"/>
	</player_stats>
	<!-- Checked By Encom 28/07/2013 -->
	<player_stats class="MUSE" level="5">
		<stats_template maxHp="339" maxMp="795" power="95" health="95" agility="100" accuracy="100" knowledge="100" will="110" walk_speed="1.5" run_speed="6" fly_speed="9" attack_speed="1.5" evasion="124" block="124" parry="124" main_hand_attack="17" main_hand_accuracy="230" main_hand_crit_rate="2" magic_accuracy="71" crit_spell="50"/>
	</player_stats>
	<!-- Checked By Encom 28/07/2013 -->
	<player_stats class="MUSE" level="6">
		<stats_template maxHp="383" maxMp="900" power="95" health="95" agility="100" accuracy="100" knowledge="100" will="110" walk_speed="1.5" run_speed="6" fly_speed="9" attack_speed="1.5" evasion="136" block="136" parry="136" main_hand_attack="17" main_hand_accuracy="238" main_hand_crit_rate="2" magic_accuracy="85" crit_spell="50"/>
	</player_stats>
	<!-- Checked By Encom 28/07/2013 -->
	<player_stats class="MUSE" level="7">
		<stats_template maxHp="429" maxMp="1005" power="95" health="95" agility="100" accuracy="100" knowledge="100" will="110" walk_speed="1.5" run_speed="6" fly_speed="9" attack_speed="1.5" evasion="148" block="148" parry="148" main_hand_attack="17" main_hand_accuracy="246" main_hand_crit_rate="2" magic_accuracy="99" crit_spell="50"/>
	</player_stats>
	<!-- Checked By Encom 28/07/2013 -->
	<player_stats class="MUSE" level="8">
		<stats_template maxHp="478" maxMp="1110" power="95" health="95" agility="100" accuracy="100" knowledge="100" will="110" walk_speed="1.5" run_speed="6" fly_speed="9" attack_speed="1.5" evasion="161" block="161" parry="161" main_hand_attack="17" main_hand_accuracy="254" main_hand_crit_rate="2" magic_accuracy="114" crit_spell="50"/>
	</player_stats>
	<!-- Checked By Encom 28/07/2013 -->
	<player_stats class="MUSE" level="9">
		<stats_template maxHp="1003" maxMp="3484" power="95" health="95" agility="100" accuracy="100" knowledge="100" will="110" walk_speed="1.5" run_speed="6" fly_speed="9" attack_speed="1.5" evasion="135" block="135" parry="135" main_hand_attack="17" main_hand_accuracy="135" main_hand_crit_rate="2" magic_accuracy="135" crit_spell="50"/>
	</player_stats>
</player_stats_templates>
