=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/player_experience_table.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="player_experience_table">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="exp" type="ExpItem" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ExpItem">
		<xs:attribute name="level" type="xs:int" use="required"/>
		<xs:attribute name="exp" type="xs:long" use="required"/>
	</xs:complexType>
</xs:schema>

=== MameDev1228/MameAion-7.8-Server/AL-Game/data/static_data/player_experience_table.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
	Player Experience Table.
	Made By Encom.
 -->
<player_experience_table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="player_experience_table.xsd">
	<exp level="1" exp="0"/>
	<exp level="2" exp="400"/>
	<exp level="3" exp="1033"/>
	<exp level="4" exp="2387"/>
	<exp level="5" exp="5234"/>
	<exp level="6" exp="8601"/>
	<exp level="7" exp="13323"/>
	<exp level="8" exp="21032"/>
	<exp level="9" exp="30972"/>
	<exp level="10" exp="43087"/>
	<exp level="11" exp="56183"/>
	<exp level="12" exp="78370"/>
	<exp level="13" exp="100203"/>
	<exp level="14" exp="129506"/>
	<exp level="15" exp="158838"/>
	<exp level="16" exp="195209"/>
	<exp level="17" exp="236101"/>
	<exp level="18" exp="312654"/>
	<exp level="19" exp="400844"/>
	<exp level="20" exp="488209"/>
	<exp level="21" exp="599161"/>
	<exp level="22" exp="778169"/>
	<exp level="23" exp="962891"/>
	<exp level="24" exp="1199117"/>
	<exp level="25" exp="1406459"/>
	<exp level="26" exp="1607073"/>
	<exp level="27" exp="1864380"/>
	<exp level="28" exp="2154562"/>
	<exp level="29" exp="2401817"/>
	<exp level="30" exp="2805357"/>
	<exp level="31" exp="3490773"/>
	<exp level="32" exp="4083698"/>
	<exp level="33" exp="4854721"/>
	<exp level="34" exp="5809416"/>
	<exp level="35" exp="7590965"/>
	<exp level="36" exp="9668316"/>
	<exp level="37" exp="11833925"/>
	<exp level="38" exp="15612813"/>
	<exp level="39" exp="17960088"/>
	<exp level="40" exp="21040392"/>
	<exp level="41" exp="25299267"/>
	<exp level="42" exp="29596360"/>
	<exp level="43" exp="34777045"/>
	<exp level="44" exp="37244961"/>
	<exp level="45" exp="39567960"/>
	<exp level="46" exp="42320163"/>
	<exp level="47" exp="45345403"/>
	<exp level="48" exp="48008552"/>
	<exp level="49" exp="50936580"/>
	<exp level="50" exp="54185061"/>
	<exp level="51" exp="57573684"/>
	<exp level="52" exp="64287820"/>
	<exp level="53" exp="69818133"/>
	<exp level="54" exp="74503034"/>
	<exp level="55" exp="78038281"/>
	<exp level="56" exp="81671945"/>
	<exp level="57" exp="86283269"/>
	<exp level="58" exp="91151545"/>
	<exp level="59" exp="96290941"/>
	<exp level="60" exp="101716397"/>
	<exp level="61" exp="105939427"/>
	<exp level="62" exp="113579483"/>
	<exp level="63" exp="119281359"/>
	<exp level="64" exp="125896094"/>
	<exp level="65" exp="133446367"/>
	<exp level="66" exp="143554432"/>
	<exp level="67" exp="153565766"/>
	<exp level="68" exp="164111289"/>
	<exp level="69" exp="175211017"/>
	<exp level="70" exp="186885407"/>
	<exp level="71" exp="199155361"/>
	<exp level="72" exp="212042226"/>
	<exp level="73" exp="225567803"/>
	<exp level="74" exp="239754344"/>
	<exp level="75" exp="254624558"/>
	<exp level="76" exp="270201616"/>
	<exp level="77" exp="286509148"/>
	<exp level="78" exp="303571254"/>
	<exp level="79" exp="321412499"/>
	<exp level="80" exp="340057920"/>
	<exp level="81" exp="359533031"/>
</player_experience_table>
